services:
  postgres:
    image: postgres:17.2
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: backend-service
    restart: always
    ports:
      - "3333:3333"
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_DATABASE: mydatabase
      APP_KEY: SnHFsJYukzt_KNon5PQWCcVCAMjsPLjP
      NODE_ENV: production
      HOST: backend-service
      LOG_LEVEL: info
      PORT: 3333
    depends_on:
      - postgres

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      API_BASE_URL: http://backend-service:3333
    depends_on:
      - backend

volumes:
  postgres-data: