version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres-db
    ports:
      - "6667:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      DATABASE_HOST: postgres
      DATABASE_PORT: 6667
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
      NODE_ENV: production
      APP_KEY: mysecret
      LOG_LEVEL: info
    depends_on:
      - postgres
    volumes:
      - ./packages/backend:/app

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      API_URL: http://backend-service:3333/api
    depends_on:
      - backend
    volumes:
      - ./packages/frontend:/app

volumes:
  postgres-data: